CREATE TABLE customer_point_policy (
    customer_id BIGINT NOT NULL,
    holding_limit BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_customer_point_policy PRIMARY KEY (customer_id),
    CONSTRAINT ck_customer_point_policy_holding_limit CHECK (holding_limit >= 0)
);

CREATE TABLE point_ledger (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id BIGINT NOT NULL,
    point_key VARCHAR(36) NOT NULL,
    request_id VARCHAR(36),
    point_type VARCHAR(30) NOT NULL,
    transaction_type VARCHAR(30),
    reference_point_key VARCHAR(36),
    order_number VARCHAR(100),
    amount BIGINT NOT NULL,
    remaining_amount BIGINT,
    balance_after BIGINT,
    expires_at TIMESTAMP WITH TIME ZONE,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    transaction_date DATE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_point_ledger PRIMARY KEY (id),
    CONSTRAINT uk_point_ledger_point_key UNIQUE (point_key),
    CONSTRAINT uk_point_ledger_request_id UNIQUE (request_id),
    CONSTRAINT uk_point_ledger_order_number UNIQUE (order_number),
    CONSTRAINT fk_point_ledger_customer_policy FOREIGN KEY (customer_id)
        REFERENCES customer_point_policy (customer_id),
    CONSTRAINT fk_point_ledger_reference FOREIGN KEY (reference_point_key)
        REFERENCES point_ledger (point_key),
    CONSTRAINT ck_point_ledger_amount CHECK (amount > 0),
    CONSTRAINT ck_point_ledger_remaining CHECK (
        (point_type = 'ACCRUAL' AND remaining_amount IS NOT NULL
            AND remaining_amount >= 0 AND remaining_amount <= amount)
        OR (point_type <> 'ACCRUAL' AND remaining_amount IS NULL)
    ),
    CONSTRAINT ck_point_ledger_balance_after CHECK (balance_after IS NULL OR balance_after >= 0),
    CONSTRAINT ck_point_ledger_accrual_fields CHECK (
        (point_type = 'ACCRUAL' AND transaction_type IS NOT NULL AND expires_at IS NOT NULL)
        OR (point_type <> 'ACCRUAL' AND transaction_type IS NULL AND expires_at IS NULL)
    ),
    CONSTRAINT ck_point_ledger_order_fields CHECK (
        (point_type IN ('USE', 'USE_CANCEL') AND order_number IS NOT NULL)
        OR (point_type IN ('ACCRUAL', 'ACCRUAL_CANCEL') AND order_number IS NULL)
    ),
    CONSTRAINT ck_point_ledger_reference_fields CHECK (
        (point_type = 'ACCRUAL' AND transaction_type <> 'EXPIRED_USE_REFUND' AND reference_point_key IS NULL)
        OR (point_type = 'ACCRUAL' AND transaction_type = 'EXPIRED_USE_REFUND' AND reference_point_key IS NOT NULL)
        OR (point_type = 'ACCRUAL_CANCEL' AND reference_point_key IS NOT NULL)
        OR (point_type = 'USE' AND reference_point_key IS NULL)
        OR (point_type = 'USE_CANCEL' AND reference_point_key IS NOT NULL)
    ),
    CONSTRAINT ck_point_ledger_internal_refund CHECK (
        transaction_type <> 'EXPIRED_USE_REFUND'
        OR (request_id IS NULL AND balance_after IS NULL)
    )
);

CREATE TABLE point_ledger_detail (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    point_key VARCHAR(36) NOT NULL,
    source_accrual_point_key VARCHAR(36) NOT NULL,
    target_accrual_point_key VARCHAR(36),
    amount BIGINT NOT NULL,
    sequence_no INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_point_ledger_detail PRIMARY KEY (id),
    CONSTRAINT uk_point_ledger_detail_sequence UNIQUE (point_key, sequence_no),
    CONSTRAINT uk_point_ledger_detail_source UNIQUE (point_key, source_accrual_point_key),
    CONSTRAINT fk_point_ledger_detail_ledger FOREIGN KEY (point_key)
        REFERENCES point_ledger (point_key),
    CONSTRAINT fk_point_ledger_detail_source FOREIGN KEY (source_accrual_point_key)
        REFERENCES point_ledger (point_key),
    CONSTRAINT fk_point_ledger_detail_target FOREIGN KEY (target_accrual_point_key)
        REFERENCES point_ledger (point_key),
    CONSTRAINT ck_point_ledger_detail_amount CHECK (amount > 0),
    CONSTRAINT ck_point_ledger_detail_sequence CHECK (sequence_no > 0)
);

CREATE INDEX idx_point_ledger_customer_date
    ON point_ledger (customer_id, transaction_date, occurred_at, id);
CREATE INDEX idx_point_ledger_customer_type_expiry
    ON point_ledger (customer_id, point_type, expires_at);
CREATE INDEX idx_point_ledger_reference ON point_ledger (reference_point_key);
CREATE INDEX idx_point_ledger_detail_source
    ON point_ledger_detail (source_accrual_point_key, id);
CREATE INDEX idx_point_ledger_detail_target
    ON point_ledger_detail (target_accrual_point_key);
